development:
  adapter: postgresql
  encoding: unicode
  database: new_octoshell_development
  user: octo
  password: 1234
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: new_octoshell_test
  user: octo
  host: localhost
  password: 1234

production:
  adapter: postgresql
  encoding: unicode
  database: new_octoshell
  host: localhost
  pool: 10
  min_messages: warning
  user: octo
  password: 1234
